### ISSUE TITLE
Don't pin dependencies

### ISSUE THREAD

**Issue by domenkozar** [miohtama/vvv#3]
Would be lovely if package only restricted to minimal versions of dependencies instead of pinning to specific version. The reason is when two pacakges pin same pacakage with different versions, everything goes to hell.

**Comment by miohtama** [comment]
It clearly says in the installation instructions that you should install VVV to a separate virtualenv only :)

**Comment by miohtama** [comment]
I'll add note to PyPi page that one should not try to pip / easy_install / buildout or whatever, because I know there will be conflicts with pylint and stuff.

**Comment by miohtama** [comment]
I updated README so that people are more aware of the issue. Thank you for bringing this out - I'll own you one beer :)
